/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../common";

export type RationalStruct = {
  numerator: PromiseOrValue<BigNumberish>;
  denominator: PromiseOrValue<BigNumberish>;
};

export type RationalStructOutput = [BigNumber, BigNumber] & {
  numerator: BigNumber;
  denominator: BigNumber;
};

export interface ProtocolInterface extends utils.Interface {
  functions: {
    "bidForNextSigner()": FunctionFragment;
    "closeDeploymentState()": FunctionFragment;
    "deployState()": FunctionFragment;
    "endRound()": FunctionFragment;
    "formNewMR(uint256)": FunctionFragment;
    "getCurrentSigner()": FunctionFragment;
    "getMoneyMixer()": FunctionFragment;
    "getReferMixer()": FunctionFragment;
    "initialMemberRegister()": FunctionFragment;
    "members(address)": FunctionFragment;
    "numberMember()": FunctionFragment;
    "onboardMember(uint256,uint256)": FunctionFragment;
    "params()": FunctionFragment;
    "receiveTransaction(uint256,uint256,uint256,uint256,uint256)": FunctionFragment;
    "refundUnsuccessSigner()": FunctionFragment;
    "requestRefer()": FunctionFragment;
    "sendReferRequest(uint256,uint256)": FunctionFragment;
    "sendTransaction(uint256,uint256)": FunctionFragment;
    "setUpMixer(address,address)": FunctionFragment;
    "signReferRequest(uint256,uint256)": FunctionFragment;
    "signTransaction(address,uint256,uint256)": FunctionFragment;
    "startNewRound()": FunctionFragment;
    "startOnboardPhaseForReferMixer()": FunctionFragment;
    "startReceivePhaseForMoneyMixer()": FunctionFragment;
    "startRequestRefer(address,uint256)": FunctionFragment;
    "startSignPhaseForMoneyMixer()": FunctionFragment;
    "startSignPhaseForReferMixer()": FunctionFragment;
    "startValidityCheckPhaseForMoneyMixer()": FunctionFragment;
    "unlockMR(uint256,uint256)": FunctionFragment;
    "validityCheck()": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "bidForNextSigner"
      | "closeDeploymentState"
      | "deployState"
      | "endRound"
      | "formNewMR"
      | "getCurrentSigner"
      | "getMoneyMixer"
      | "getReferMixer"
      | "initialMemberRegister"
      | "members"
      | "numberMember"
      | "onboardMember"
      | "params"
      | "receiveTransaction"
      | "refundUnsuccessSigner"
      | "requestRefer"
      | "sendReferRequest"
      | "sendTransaction"
      | "setUpMixer"
      | "signReferRequest"
      | "signTransaction"
      | "startNewRound"
      | "startOnboardPhaseForReferMixer"
      | "startReceivePhaseForMoneyMixer"
      | "startRequestRefer"
      | "startSignPhaseForMoneyMixer"
      | "startSignPhaseForReferMixer"
      | "startValidityCheckPhaseForMoneyMixer"
      | "unlockMR"
      | "validityCheck"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "bidForNextSigner",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "closeDeploymentState",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "deployState",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "endRound", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "formNewMR",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "getCurrentSigner",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getMoneyMixer",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getReferMixer",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "initialMemberRegister",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "members",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "numberMember",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "onboardMember",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(functionFragment: "params", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "receiveTransaction",
    values: [
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "refundUnsuccessSigner",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "requestRefer",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "sendReferRequest",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "sendTransaction",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "setUpMixer",
    values: [PromiseOrValue<string>, PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "signReferRequest",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "signTransaction",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "startNewRound",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "startOnboardPhaseForReferMixer",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "startReceivePhaseForMoneyMixer",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "startRequestRefer",
    values: [PromiseOrValue<string>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "startSignPhaseForMoneyMixer",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "startSignPhaseForReferMixer",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "startValidityCheckPhaseForMoneyMixer",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "unlockMR",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "validityCheck",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "bidForNextSigner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "closeDeploymentState",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "deployState",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "endRound", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "formNewMR", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getCurrentSigner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMoneyMixer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getReferMixer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "initialMemberRegister",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "members", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "numberMember",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "onboardMember",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "params", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "receiveTransaction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "refundUnsuccessSigner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requestRefer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "sendReferRequest",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "sendTransaction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setUpMixer", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "signReferRequest",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "signTransaction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "startNewRound",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "startOnboardPhaseForReferMixer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "startReceivePhaseForMoneyMixer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "startRequestRefer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "startSignPhaseForMoneyMixer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "startSignPhaseForReferMixer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "startValidityCheckPhaseForMoneyMixer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "unlockMR", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "validityCheck",
    data: BytesLike
  ): Result;

  events: {
    "RequestRefer(address)": EventFragment;
    "SendTransactionRequest(address,uint256,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "RequestRefer"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "SendTransactionRequest"): EventFragment;
}

export interface RequestReferEventObject {
  signer: string;
}
export type RequestReferEvent = TypedEvent<[string], RequestReferEventObject>;

export type RequestReferEventFilter = TypedEventFilter<RequestReferEvent>;

export interface SendTransactionRequestEventObject {
  signer: string;
  index: BigNumber;
  e: BigNumber;
}
export type SendTransactionRequestEvent = TypedEvent<
  [string, BigNumber, BigNumber],
  SendTransactionRequestEventObject
>;

export type SendTransactionRequestEventFilter =
  TypedEventFilter<SendTransactionRequestEvent>;

export interface Protocol extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: ProtocolInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    bidForNextSigner(
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    closeDeploymentState(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    deployState(
      overrides?: CallOverrides
    ): Promise<
      [boolean, BigNumber, BigNumber, boolean] & {
        isDeploymentEnd: boolean;
        numInitialMember: BigNumber;
        endblock: BigNumber;
        firstSignerSetUp: boolean;
      }
    >;

    endRound(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    formNewMR(
      amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    getCurrentSigner(overrides?: CallOverrides): Promise<[string]>;

    getMoneyMixer(overrides?: CallOverrides): Promise<[string]>;

    getReferMixer(overrides?: CallOverrides): Promise<[string]>;

    initialMemberRegister(
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    members(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    numberMember(overrides?: CallOverrides): Promise<[BigNumber]>;

    onboardMember(
      e: PromiseOrValue<BigNumberish>,
      s: PromiseOrValue<BigNumberish>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    params(
      overrides?: CallOverrides
    ): Promise<
      [RationalStructOutput, BigNumber, BigNumber, BigNumber] & {
        parentFee: RationalStructOutput;
        protocolFee: BigNumber;
        joinFee: BigNumber;
        signerDepositFee: BigNumber;
      }
    >;

    receiveTransaction(
      money: PromiseOrValue<BigNumberish>,
      rho: PromiseOrValue<BigNumberish>,
      delta: PromiseOrValue<BigNumberish>,
      omega: PromiseOrValue<BigNumberish>,
      sigma: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    refundUnsuccessSigner(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    requestRefer(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    sendReferRequest(
      nonce: PromiseOrValue<BigNumberish>,
      e: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    sendTransaction(
      index: PromiseOrValue<BigNumberish>,
      e: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setUpMixer(
      _moneyMixer: PromiseOrValue<string>,
      _referMixer: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    signReferRequest(
      nonce: PromiseOrValue<BigNumberish>,
      s: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    signTransaction(
      account: PromiseOrValue<string>,
      e: PromiseOrValue<BigNumberish>,
      r: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    startNewRound(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    startOnboardPhaseForReferMixer(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    startReceivePhaseForMoneyMixer(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    startRequestRefer(
      account: PromiseOrValue<string>,
      nonce: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    startSignPhaseForMoneyMixer(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    startSignPhaseForReferMixer(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    startValidityCheckPhaseForMoneyMixer(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    unlockMR(
      index: PromiseOrValue<BigNumberish>,
      e: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    validityCheck(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  bidForNextSigner(
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  closeDeploymentState(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  deployState(
    overrides?: CallOverrides
  ): Promise<
    [boolean, BigNumber, BigNumber, boolean] & {
      isDeploymentEnd: boolean;
      numInitialMember: BigNumber;
      endblock: BigNumber;
      firstSignerSetUp: boolean;
    }
  >;

  endRound(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  formNewMR(
    amount: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  getCurrentSigner(overrides?: CallOverrides): Promise<string>;

  getMoneyMixer(overrides?: CallOverrides): Promise<string>;

  getReferMixer(overrides?: CallOverrides): Promise<string>;

  initialMemberRegister(
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  members(
    arg0: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<boolean>;

  numberMember(overrides?: CallOverrides): Promise<BigNumber>;

  onboardMember(
    e: PromiseOrValue<BigNumberish>,
    s: PromiseOrValue<BigNumberish>,
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  params(
    overrides?: CallOverrides
  ): Promise<
    [RationalStructOutput, BigNumber, BigNumber, BigNumber] & {
      parentFee: RationalStructOutput;
      protocolFee: BigNumber;
      joinFee: BigNumber;
      signerDepositFee: BigNumber;
    }
  >;

  receiveTransaction(
    money: PromiseOrValue<BigNumberish>,
    rho: PromiseOrValue<BigNumberish>,
    delta: PromiseOrValue<BigNumberish>,
    omega: PromiseOrValue<BigNumberish>,
    sigma: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  refundUnsuccessSigner(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  requestRefer(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  sendReferRequest(
    nonce: PromiseOrValue<BigNumberish>,
    e: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  sendTransaction(
    index: PromiseOrValue<BigNumberish>,
    e: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setUpMixer(
    _moneyMixer: PromiseOrValue<string>,
    _referMixer: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  signReferRequest(
    nonce: PromiseOrValue<BigNumberish>,
    s: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  signTransaction(
    account: PromiseOrValue<string>,
    e: PromiseOrValue<BigNumberish>,
    r: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  startNewRound(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  startOnboardPhaseForReferMixer(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  startReceivePhaseForMoneyMixer(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  startRequestRefer(
    account: PromiseOrValue<string>,
    nonce: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  startSignPhaseForMoneyMixer(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  startSignPhaseForReferMixer(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  startValidityCheckPhaseForMoneyMixer(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  unlockMR(
    index: PromiseOrValue<BigNumberish>,
    e: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  validityCheck(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    bidForNextSigner(overrides?: CallOverrides): Promise<void>;

    closeDeploymentState(overrides?: CallOverrides): Promise<void>;

    deployState(
      overrides?: CallOverrides
    ): Promise<
      [boolean, BigNumber, BigNumber, boolean] & {
        isDeploymentEnd: boolean;
        numInitialMember: BigNumber;
        endblock: BigNumber;
        firstSignerSetUp: boolean;
      }
    >;

    endRound(overrides?: CallOverrides): Promise<void>;

    formNewMR(
      amount: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    getCurrentSigner(overrides?: CallOverrides): Promise<string>;

    getMoneyMixer(overrides?: CallOverrides): Promise<string>;

    getReferMixer(overrides?: CallOverrides): Promise<string>;

    initialMemberRegister(overrides?: CallOverrides): Promise<void>;

    members(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<boolean>;

    numberMember(overrides?: CallOverrides): Promise<BigNumber>;

    onboardMember(
      e: PromiseOrValue<BigNumberish>,
      s: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    params(
      overrides?: CallOverrides
    ): Promise<
      [RationalStructOutput, BigNumber, BigNumber, BigNumber] & {
        parentFee: RationalStructOutput;
        protocolFee: BigNumber;
        joinFee: BigNumber;
        signerDepositFee: BigNumber;
      }
    >;

    receiveTransaction(
      money: PromiseOrValue<BigNumberish>,
      rho: PromiseOrValue<BigNumberish>,
      delta: PromiseOrValue<BigNumberish>,
      omega: PromiseOrValue<BigNumberish>,
      sigma: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    refundUnsuccessSigner(overrides?: CallOverrides): Promise<void>;

    requestRefer(overrides?: CallOverrides): Promise<void>;

    sendReferRequest(
      nonce: PromiseOrValue<BigNumberish>,
      e: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    sendTransaction(
      index: PromiseOrValue<BigNumberish>,
      e: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    setUpMixer(
      _moneyMixer: PromiseOrValue<string>,
      _referMixer: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    signReferRequest(
      nonce: PromiseOrValue<BigNumberish>,
      s: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    signTransaction(
      account: PromiseOrValue<string>,
      e: PromiseOrValue<BigNumberish>,
      r: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    startNewRound(overrides?: CallOverrides): Promise<void>;

    startOnboardPhaseForReferMixer(overrides?: CallOverrides): Promise<void>;

    startReceivePhaseForMoneyMixer(overrides?: CallOverrides): Promise<void>;

    startRequestRefer(
      account: PromiseOrValue<string>,
      nonce: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    startSignPhaseForMoneyMixer(overrides?: CallOverrides): Promise<void>;

    startSignPhaseForReferMixer(overrides?: CallOverrides): Promise<void>;

    startValidityCheckPhaseForMoneyMixer(
      overrides?: CallOverrides
    ): Promise<void>;

    unlockMR(
      index: PromiseOrValue<BigNumberish>,
      e: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    validityCheck(overrides?: CallOverrides): Promise<void>;
  };

  filters: {
    "RequestRefer(address)"(
      signer?: PromiseOrValue<string> | null
    ): RequestReferEventFilter;
    RequestRefer(
      signer?: PromiseOrValue<string> | null
    ): RequestReferEventFilter;

    "SendTransactionRequest(address,uint256,uint256)"(
      signer?: PromiseOrValue<string> | null,
      index?: null,
      e?: null
    ): SendTransactionRequestEventFilter;
    SendTransactionRequest(
      signer?: PromiseOrValue<string> | null,
      index?: null,
      e?: null
    ): SendTransactionRequestEventFilter;
  };

  estimateGas: {
    bidForNextSigner(
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    closeDeploymentState(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    deployState(overrides?: CallOverrides): Promise<BigNumber>;

    endRound(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    formNewMR(
      amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    getCurrentSigner(overrides?: CallOverrides): Promise<BigNumber>;

    getMoneyMixer(overrides?: CallOverrides): Promise<BigNumber>;

    getReferMixer(overrides?: CallOverrides): Promise<BigNumber>;

    initialMemberRegister(
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    members(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    numberMember(overrides?: CallOverrides): Promise<BigNumber>;

    onboardMember(
      e: PromiseOrValue<BigNumberish>,
      s: PromiseOrValue<BigNumberish>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    params(overrides?: CallOverrides): Promise<BigNumber>;

    receiveTransaction(
      money: PromiseOrValue<BigNumberish>,
      rho: PromiseOrValue<BigNumberish>,
      delta: PromiseOrValue<BigNumberish>,
      omega: PromiseOrValue<BigNumberish>,
      sigma: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    refundUnsuccessSigner(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    requestRefer(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    sendReferRequest(
      nonce: PromiseOrValue<BigNumberish>,
      e: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    sendTransaction(
      index: PromiseOrValue<BigNumberish>,
      e: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setUpMixer(
      _moneyMixer: PromiseOrValue<string>,
      _referMixer: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    signReferRequest(
      nonce: PromiseOrValue<BigNumberish>,
      s: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    signTransaction(
      account: PromiseOrValue<string>,
      e: PromiseOrValue<BigNumberish>,
      r: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    startNewRound(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    startOnboardPhaseForReferMixer(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    startReceivePhaseForMoneyMixer(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    startRequestRefer(
      account: PromiseOrValue<string>,
      nonce: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    startSignPhaseForMoneyMixer(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    startSignPhaseForReferMixer(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    startValidityCheckPhaseForMoneyMixer(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    unlockMR(
      index: PromiseOrValue<BigNumberish>,
      e: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    validityCheck(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    bidForNextSigner(
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    closeDeploymentState(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    deployState(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    endRound(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    formNewMR(
      amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    getCurrentSigner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getMoneyMixer(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getReferMixer(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    initialMemberRegister(
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    members(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    numberMember(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    onboardMember(
      e: PromiseOrValue<BigNumberish>,
      s: PromiseOrValue<BigNumberish>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    params(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    receiveTransaction(
      money: PromiseOrValue<BigNumberish>,
      rho: PromiseOrValue<BigNumberish>,
      delta: PromiseOrValue<BigNumberish>,
      omega: PromiseOrValue<BigNumberish>,
      sigma: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    refundUnsuccessSigner(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    requestRefer(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    sendReferRequest(
      nonce: PromiseOrValue<BigNumberish>,
      e: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    sendTransaction(
      index: PromiseOrValue<BigNumberish>,
      e: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setUpMixer(
      _moneyMixer: PromiseOrValue<string>,
      _referMixer: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    signReferRequest(
      nonce: PromiseOrValue<BigNumberish>,
      s: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    signTransaction(
      account: PromiseOrValue<string>,
      e: PromiseOrValue<BigNumberish>,
      r: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    startNewRound(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    startOnboardPhaseForReferMixer(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    startReceivePhaseForMoneyMixer(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    startRequestRefer(
      account: PromiseOrValue<string>,
      nonce: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    startSignPhaseForMoneyMixer(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    startSignPhaseForReferMixer(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    startValidityCheckPhaseForMoneyMixer(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    unlockMR(
      index: PromiseOrValue<BigNumberish>,
      e: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    validityCheck(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
